package com.aios.app_registry;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * A service that discovers and keeps track of all applications generated by the AI.
 */
public class AppRegistry {

    private static final String APPS_BASE_DIR = "generated_apps/";
    private final List<AppInfo> appList;

    public AppRegistry() {
        this.appList = new ArrayList<>();
    }

    /**
     * Scans the application directory to find all generated apps and updates the registry.
     */
    public void scanForApps() {
        appList.clear();
        File baseDir = new File(APPS_BASE_DIR);
        File[] appDirs = baseDir.listFiles(File::isDirectory);

        if (appDirs != null) {
            for (File appDir : appDirs) {
                AppInfo appInfo = new AppInfo(appDir.getName(), appDir.lastModified());
                appList.add(appInfo);
            }
        }
    }

    /**
     * Returns a read-only list of the discovered applications.
     * @return An unmodifiable list of AppInfo objects.
     */
    public List<AppInfo> getAppList() {
        return Collections.unmodifiableList(appList);
    }
}
